FROM php:8.2-apache

RUN docker-php-ext-install pdo pdo_mysql mysqli
RUN a2enmod rewrite

COPY apache-vhost.attack.conf /etc/apache2/sites-available/000-default.conf
RUN a2dissite 000-default.conf 2>/dev/null || true \
 && a2ensite 000-default.conf

RUN mkdir -p /var/log/apache2

EXPOSE 80
